[package]
name = "qptrie"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]

[dependencies]
clippy = {version = "*", optional = true}
debug_unreachable = "~0"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
